### ISSUE TITLE
Compatibility to TYPO3 v7+

### ISSUE THREAD

**Issue by stephankellermayr** [jainishsenjaliya/js_faq#1]
What a about a new version/generation for TYPO3 v7?
Do you have any plans for that, or would it be helpful if i contribute to this project?

It would be nice to release a new/reworked version focusing on the new TYPO3 (perhaps with no downward-compatibility to any older version).

What do you think?

**Comment by jainishsenjaliya** [comment]
Yes my friend, i have planned for that.

It will be available with in few days..

**Comment by stephankellermayr** [comment]
good news! thanks for your great work!

**Comment by jainishsenjaliya** [comment]
Compatibility with TYPO3 7.6.4 has been released :+1:
