### ISSUE TITLE
Set Links in description-Field

### ISSUE THREAD

**Issue by sarahhoppe** [jainishsenjaliya/js_faq#4]
I try to set links at the description field. In DB the links save correctly, but in FE ther is only a <link ..>-tag. I also tried to set the parsefunc to the description field but nathing was change at FE.
Is there any possibility to set links?

**Comment by jainishsenjaliya** [comment]
This issue has been solved and please find out latest version

https://github.com/jainishsenjaliya/js_faq/releases

**Comment by sarahhoppe** [comment]
Thanx. Could you please upload the newest version to ter?

**Comment by jainishsenjaliya** [comment]
Tomorrow I will do

Thx

**Comment by jainishsenjaliya** [comment]
you may check latest version in TER also

**Comment by sarahhoppe** [comment]
I checked the issue whit the newest version, but the problem is already there. Make a link inside description isn't possible.

**Comment by jainishsenjaliya** [comment]
I have just tested it..  it's working fine for me..

Can you please complete remove old extension

Thn after install latest one

Thanks for informing 😃

**Comment by sarahhoppe** [comment]
Also after remove and new install of the extension the problem exist. The output in FE looks like <link btntuerkis="" -="" 650="">.
