### ISSUE TITLE
Error with TYPO3 7.6.9

### ISSUE THREAD

**Issue by Hobokens** [jainishsenjaliya/js_faq#5]
Hi,
installing the your extension I get the following error:
`PHP Runtime Deprecation Notice: Non-static method JS\JsFaq\Service\Configuration::template() should not be called statically, assuming $this from incompatible context in /html/typo3/typo3conf/ext/js_faq/Classes/Controller/FAQController.php line 68`

Regards
Hobokens

**Comment by jainishsenjaliya** [comment]
I have tested it now.. it's working fine for me.. in 7.6.9 as well

Can you please clear your cache and install it again.

**Comment by Hobokens** [comment]
I tested it again:
I install  the extension from the repository, 2) Include the static template, 3) add the pid of the folder where I have the Questions and Answers in the constants 4) add a question with an answer and a cateogry in this folder 5) add the plugin on a page and choose a category.
When I visit the web page I still get the error. Do I miss a configuration step?

**Comment by jainishsenjaliya** [comment]
Can you send me snap.

So I can easily get your point

You can directly mail me on jainishsenjaliya@gmail.com

**Comment by Hobokens** [comment]
Thanks for the help. I've sent you a mail.

**Comment by Hobokens** [comment]
Thanks for your great help. Everything is fine now.
