### ISSUE TITLE
Hide all/Show all button is not using f:translate

### ISSUE THREAD

**Issue by mblaschke** [jainishsenjaliya/js_faq#9]
There should be no static text inside templates, please replace it with f:translate and xlf files :)

https://github.com/jainishsenjaliya/js_faq/blob/master/Resources/Private/Partials/Template/Default.html#L7

**Comment by jainishsenjaliya** [comment]
Thanks for update.. Currently i am working on this.. will be update soon in repository.

**Comment by jainishsenjaliya** [comment]
Is this real translation of Show All / Hide all ??
"Alle anzeigen / Alle verbergen"

can you please send me correct text

**Comment by jainishsenjaliya** [comment]
Done in 5.4.0 version.
